import html2canvas from 'html2canvas';
import type { TimelineRow, TripMetadata } from '@/types/trip';

export interface ImageExportOptions {
  destination: string;
  plan: string;
  timeline: TimelineRow[];
  metadata: TripMetadata;
  filename?: string;
  format?: 'png' | 'jpeg';
  quality?: number;
}

/**
 * Export timeline to image (PNG or JPEG)
 *
 * @param options - Export options including timeline data and format preferences
 * @returns Promise that resolves when image is generated and downloaded
 */
export async function exportToImage(options: ImageExportOptions): Promise<void> {
  const {
    destination,
    plan,
    timeline,
    metadata,
    filename,
    format = 'png',
    quality = 0.95
  } = options;

  // Create a temporary container for rendering
  const container = document.createElement('div');
  container.style.cssText = `
    position: absolute;
    left: -9999px;
    width: 1200px;
    background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
    padding: 60px;
    font-family: system-ui, -apple-system, sans-serif;
    border-radius: 16px;
  `;
  document.body.appendChild(container);

  // Build HTML content
  container.innerHTML = `
    <div style="color: #f1f5f9;">
      <div style="margin-bottom: 40px; border-bottom: 3px solid #3b82f6; padding-bottom: 30px;">
        <h1 style="font-size: 42px; font-weight: bold; margin: 0 0 15px 0; color: #f1f5f9;">
          ${destination} 여행 일정
        </h1>
        <p style="font-size: 20px; color: #94a3b8; margin: 8px 0;">
          ${plan}
        </p>
        <div style="margin-top: 20px; font-size: 16px; color: #cbd5e1; display: flex; gap: 30px; flex-wrap: wrap;">
          <div>📅 ${metadata.departureDate} ~ ${metadata.returnDate}</div>
          <div>👥 ${metadata.travelers}명</div>
          <div>🛫 ${metadata.departureCity}</div>
          ${metadata.budget ? `<div>💰 ${metadata.budget.toLocaleString()}원</div>` : ''}
        </div>
      </div>

      ${generateTimelineHtml(timeline)}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #334155; text-align: center; color: #64748b; font-size: 14px;">
        Generated by Trip Planner · ${new Date().toLocaleDateString('ko-KR')}
      </div>
    </div>
  `;

  try {
    // Convert HTML to canvas
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: null
    });

    // Convert canvas to blob
    const blob = await new Promise<Blob>((resolve, reject) => {
      canvas.toBlob(
        (blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Failed to create blob'));
          }
        },
        format === 'jpeg' ? 'image/jpeg' : 'image/png',
        quality
      );
    });

    // Download image
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const imageFilename = filename || `${destination}_trip_${new Date().getTime()}.${format}`;
    link.download = imageFilename;
    link.href = url;
    link.click();

    // Clean up
    URL.revokeObjectURL(url);
  } finally {
    // Clean up
    document.body.removeChild(container);
  }
}

/**
 * Export timeline element directly (if rendering from existing DOM)
 *
 * @param elementId - ID of the DOM element to capture
 * @param filename - Output filename
 * @param format - Image format (png or jpeg)
 * @param quality - Image quality (0-1)
 */
export async function exportElementToImage(
  elementId: string,
  filename?: string,
  format: 'png' | 'jpeg' = 'png',
  quality: number = 0.95
): Promise<void> {
  const element = document.getElementById(elementId);

  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: null
    });

    const blob = await new Promise<Blob>((resolve, reject) => {
      canvas.toBlob(
        (blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Failed to create blob'));
          }
        },
        format === 'jpeg' ? 'image/jpeg' : 'image/png',
        quality
      );
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = filename || `timeline_${new Date().getTime()}.${format}`;
    link.href = url;
    link.click();

    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Image export error:', error);
    throw error;
  }
}

/**
 * Generate HTML for timeline rows
 */
function generateTimelineHtml(timeline: TimelineRow[]): string {
  const groupedByDay = timeline.reduce((acc, row) => {
    if (!acc[row.day]) {
      acc[row.day] = [];
    }
    acc[row.day].push(row);
    return acc;
  }, {} as Record<number, TimelineRow[]>);

  return Object.entries(groupedByDay)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([day, rows]) => {
      const firstRow = rows[0];
      return `
        <div style="margin-bottom: 30px;">
          <div style="background: rgba(59, 130, 246, 0.15); padding: 16px 20px; border-radius: 12px; margin-bottom: 20px; backdrop-filter: blur(10px);">
            <div style="display: flex; align-items: center; gap: 15px;">
              <div style="background: #3b82f6; color: white; width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 18px; box-shadow: 0 4px 6px rgba(59, 130, 246, 0.3);">
                ${day}
              </div>
              <span style="font-size: 20px; font-weight: 600; color: #e2e8f0;">
                ${new Date(firstRow.date).toLocaleDateString('ko-KR', {
                  month: 'long',
                  day: 'numeric',
                  weekday: 'short'
                })}
              </span>
            </div>
          </div>

          <div style="margin-left: 30px; display: grid; gap: 15px;">
            ${rows.map(row => `
              <div style="padding: 18px; background: rgba(30, 41, 59, 0.6); border-left: 4px solid ${getCategoryColor(row.category)}; border-radius: 8px; backdrop-filter: blur(10px);">
                <div style="display: flex; gap: 20px; align-items: flex-start;">
                  <span style="font-size: 16px; font-weight: 600; color: #94a3b8; min-width: 80px; font-family: monospace;">
                    ${row.time}
                  </span>
                  <div style="flex: 1;">
                    <div style="font-size: 18px; font-weight: 600; color: #f1f5f9; margin-bottom: 6px;">
                      ${getCategoryIcon(row.category)} ${row.activity}
                    </div>
                    <div style="font-size: 15px; color: #cbd5e1;">
                      📍 ${row.location}
                    </div>
                    ${row.notes ? `<div style="font-size: 14px; color: #94a3b8; margin-top: 6px; font-style: italic;">💬 ${row.notes}</div>` : ''}
                  </div>
                  ${row.cost ? `
                    <div style="font-size: 16px; color: #fbbf24; font-weight: 600; white-space: nowrap;">
                      ${row.cost.amount.toLocaleString()} ${row.cost.currency}
                    </div>
                  ` : ''}
                </div>
              </div>
            `).join('')}
          </div>
        </div>
      `;
    })
    .join('');
}

/**
 * Get color for category
 */
function getCategoryColor(category: TimelineRow['category']): string {
  const colors = {
    transport: '#3b82f6',
    activity: '#10b981',
    food: '#f59e0b',
    accommodation: '#8b5cf6',
    free: '#6b7280'
  };
  return colors[category] || '#6b7280';
}

/**
 * Get icon for category
 */
function getCategoryIcon(category: TimelineRow['category']): string {
  const icons = {
    transport: '✈️',
    activity: '🎯',
    food: '🍽️',
    accommodation: '🏨',
    free: '🎪'
  };
  return icons[category] || '📌';
}
